### ISSUE TITLE
New data source: MAUDE (Manufacturer and User Facility Device Experience Database)

### ISSUE THREAD

**Issue by marks** [FDA/openfda#10]
Link: http://www.fda.gov/MedicalDevices/DeviceRegulationandGuidance/PostmarketRequirements/ReportingAdverseEvents/ucm127891.htm

Like FAERS/AERS, this dataset has a high barrier of entry for developers, consumers, and probably many researchers too.

**Comment by mattmo** [comment]
Both MAUDE and R&L have been live on the site for some time now. Closing. Please open a new issue if you have any problems. Thanks!
