### ISSUE TITLE
Update on Events Database

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#100]
Hello,

I noticed that the Events database seems to be missing some information. Or is there a reason my search is not finding these results?
![fda maude report date](https://user-images.githubusercontent.com/43623659/49658732-61a9cb00-fa08-11e8-995e-7f00c79f2639.png)
![open fda maude api date report](https://user-images.githubusercontent.com/43623659/49658733-62426180-fa08-11e8-91f1-a698b1baaaec.png)

**Comment by CalebYates1** [comment]
I knew they were 2 different records, but I was referring to that the api screenshot was of the most recent event in the api and that it wasnt consistent with the most recent available information in the FDA. I can see that the system has been update. Thank you very much for helping me!

**Comment by dkrylovsb** [comment]
Oh, understand. Thanks for clarifying. Yes, we did push an update through.
