### ISSUE TITLE
query by manufacturer_name

### ISSUE THREAD

**Issue by LeilyR** [FDA/openfda#102]
I am trying to see the list of all existing manufacturers and search for a certain name. 
I tried something like this to get the list of existing manufacturer but it fails
https://api.fda.gov/drug/event.json?_exists_:manufacturer_name&limit=3
Is there a way to do so?
Also to query for a certain manufacturer I have tried this :
https://api.fda.gov/drug/event.json?search=manufacturer_name:["name"]+AND+effective_time:[20110101+TO+20120101]&limit=1
which also failed. Could you please tell me what I do wrong? thanks a lot!

**Comment by dkrylovsb** [comment]
The first query needs to be corrected as follows:

`https://api.fda.gov/drug/event.json?search=_exists_:patient.drug.openfda.manufacturer_name&limit=3`

The second one also needs to change:

`https://api.fda.gov/drug/event.json?search=manufacturer_name:name+AND+effective_time:[20110101+TO+20120101]&limit=1`
