### ISSUE TITLE
Add link header with "next" parameter for pagination

### ISSUE THREAD

**Issue by beckyconning** [FDA/openfda#103]
For example: https://developer.github.com/v3/guides/traversing-with-pagination/

The page size can be determined by the recommended size, e.g. 100.

E.g. the header after the first request would be
```
Link: <https://api.fda.gov/device/510k.json?search=advisory_committee:cv&limit=100&skip=100>; rel="next"
```
the header after the second request would be
```
Link: <https://api.fda.gov/device/510k.json?search=advisory_committee:cv&limit=100&skip=200>; rel="next"
```
and on the last page the header is omitted.

**Comment by beckyconning** [comment]
We'd need to know whether we are on the last page or not. One way of doing this for the search requests would be to do a count the other would be to change the `es_search_params.size` to be one more than we need and checking for that extra result.

**Comment by beckyconning** [comment]
Actually I'm wrong Elasticsearch returns this info.

**Comment by beckyconning** [comment]
https://tools.ietf.org/html/rfc5988#page-6

**Comment by beckyconning** [comment]
Using the "Link" header with the "next" relation is the only standardised way of providing pagination over HTTP. Supporting this allows an ecosystem of applications to use this API without custom integration and with the simplest possible user experience. There is a straightforward PR (+11 −3) open which adds this capability to the API as a non-breaking change.

**Comment by dkrylovsb** [comment]
Hi @beckyconning , we'd need some time on our end to QA your PR, write automated tests for it and then hopefully push to Production. 

Just curious why it's imperative to have this header on your side? Every API response already contains the `skip`, `limit`, and `total` fields within the metadata section, which give sufficient information to do paging.

**Comment by beckyconning** [comment]
Thanks for your thoughtful reply @dkrylovsb!

Although this is sufficient information it's not provided in a standardised way. APIs which support this standard can be accessed by applications without customised configuration.

**Comment by beckyconning** [comment]
An ideal UX for consuming the current data from the API in a paginated manner is for users to provide a URL for an initial request as well as the desired number of records per page. Then users will need to select the total field from the data.

To support this UX the application will then need to manage the addition of the records per page and checking that the total has not been reached itself.

However if this PR is merged a UX can be provided where the user simply provides the URL.

To support this improved UX the application will not need to do anything other than stopping when the header is no longer present.

So the addition of the only standard for pagination on the web is a win-win for both users and applications.

**Comment by beckyconning** [comment]
An ideal UX for consuming the current data from the API in a paginated manner is for users to provide a URL for an initial request as well as the desired number of records per page. Then users will need to select the total field from the data and provide the URL again as a template such as `https://api.fda.gov/animalandveterinary/event.json?skip={{offset}}&limit={{per_page}}`.

To support this UX the application will then need to manage the addition of the records per page, checking that the total has not been reached and rendering of the templated URL for subsequent requests itself.

However if this PR is merged a UX can be provided where the user simply provides the URL.

To support this improved UX the application will not need to do anything other than stopping when the header is no longer present.

So the addition of the only standard for pagination on the web is a win-win for both users and applications.

**Comment by beckyconning** [comment]
So in short this change allows applications to integrate this API with less engineering work whilst also providing a stronger user experience. This will allow more people to get value from the data this API provides.

**Comment by dkrylovsb** [comment]
Thank you for your contribution @beckyconning! We are working on integrating into Production this week.

**Comment by beckyconning** [comment]
Fantastic, thank you!

**Comment by beckyconning** [comment]
Appears to be done!

**Comment by beckyconning** [comment]
If you use the api key as the basic auth user header instead of in the URL this works great. Thanks so much!
