### ISSUE TITLE
Adverse Event API Missing Data.

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#105]
The Adverse Event API is missing data present in the FDA database. The database is showing no mdr_text information. The front-facing database does show this information is available. Is it possible to get this information back?

https://api.fda.gov/device/event.json?search=(device.model_number:3662)+AND+(date_report:20190831)+AND+(device.manufacturer_d_name:ST.%20JUDE%20MEDICAL)&skip=1&limit=1

![Screen Shot 2019-09-30 at 12 49 40 PM](https://user-images.githubusercontent.com/43623659/65902931-0ecb4680-e381-11e9-93f2-fed2cbf246ef.png)

**Comment by CalebYates1** [comment]
Hello, just wanted to see if there was a response to this question.

**Comment by dkrylovsb** [comment]
We have verified `mdr_text` is provided by the API:

https://api.fda.gov/device/event.json?search=(device.model_number:3662)+AND+(date_of_event:20190802)
