### ISSUE TITLE
Mystery drugs in the animal and veterinary adverse events dataset

### ISSUE THREAD

**Issue by beckyconning** [FDA/openfda#109]
There are many drugs listed in the animal and veterinary adverse events dataset which don't contain active ingredient name nor ATC code.

What do these represent?

**Comment by dkrylovsb** [comment]
@beckyconning The following two queries indicate that all adverse event records have an ATC Vet code and active ingredient:

https://api.fda.gov/animalandveterinary/event.json?search=_missing_:drug.atc_vet_code
https://api.fda.gov/animalandveterinary/event.json?search=_missing_:drug.active_ingredients

I am thus closing this issue; however, please feel free to re-open in case I missed something.
