### ISSUE TITLE
FAERS quarterly updates

### ISSUE THREAD

**Issue by JeremyHennessy** [FDA/openfda#113]
I have noticed that the FAERS dataset has not been updated since 2019 Q1. Whereas 2019 q2 and q3 are now available. 

Is it possible that the FDA website changes (which occurred shortly after q1 release) affected the current script used to extract the latest quarters?

 FAERS_CURRENT = 'https://fis.fda.gov/extensions/FPD-QDE-FAERS/FPD-QDE-FAERS.html'

**Comment by dkrylovsb** [comment]
Thank you for alerting us. Fixed.

**Comment by JeremyHennessy** [comment]
No problem, thanks for the update.  

I noticed the fix added the new quarters in the "All other data" fields when downloading and not 2019 q2 and q3 files.  Will this also be corrected or will new quarters just be added the "All other data"?

**Comment by dkrylovsb** [comment]
Yup, will be fixed in tomorrow's run.

**Comment by JeremyHennessy** [comment]
Hi Denis, not sure if the issue was a temporary fix but it appears that the last quarter of 2019 has not been added yet to the openFDA datasets.
