### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by paulbsanders** [FDA/openfda#114]
With Python 2 coming to end of life on January 1, will support for Python 3 be added to this project?

**Comment by dkrylovsb** [comment]
We're looking into this.

**Comment by JCui2017** [comment]
I tested the code below in Python 3 and it works nicely:

`
import requests
import json

url = 'https://api.fda.gov/drug/ndc.json?search=brand_name:"zyrtec"&limit=1'
r = requests.get(url)

print(json.dumps(r.json(), indent=2))
`

**Comment by dkrylovsb** [comment]
Done.
