### ISSUE TITLE
Adverse Event Data Not Up To Date

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#117]
The FDA MAUDE main database has information up thru December 2019, but the API is only pulling data  thru November 2019. When will this data get updated to have the up to date information?

**Comment by CalebYates1** [comment]
Just wanted to follow up with this and see when this information would be updated?

**Comment by CalebYates1** [comment]
May I ask if this is an issue with the FDA providing the information to the project?

**Comment by beardedfinch** [comment]
Hi @CalebYates1 , I'm Jack with the openFDA Team. The temporary suspension of updates to the openFDA datasets has ended. We're in the process of updating all datasets. The Device Adverse Events dataset is now updated. Please stay tuned in to the [API Status page](https://open.fda.gov/about/status/) for update details on other datasets. Thank you!
