### ISSUE TITLE
Where should the dataset be placed in order to run the api locally?

### ISSUE THREAD

**Issue by evgakis** [FDA/openfda#118]
Hi, to everyone,
I would like to ask about where should I place the dataset which will be downloaded from here 
[https://open.fda.gov/downloads/](https://open.fda.gov/downloads/)

I have downloaded locally the code from this link
[https://github.com/FDA/openfda](https://github.com/FDA/openfda)

And there are many folders and subfolders there. Where is the folder where the data should be placed in? For example I would like to call the following url and get results
[localhost:8000/drug/event.json?api_key=&search=_exists_:(patient.drug.openfda.generic_name)+AND+patient.reaction.reactionmeddrapt.exact:("CONFUSIONAL%20STATE")+AND+_exists_:(patient.reaction.reactionmeddrapt.exact)+AND+receiptdate:([1989-06-30+TO+2020-02-13])&limit=1&skip=0 ](localhost:8000/drug/event.json?api_key=&search=_exists_:(patient.drug.openfda.generic_name)+AND+patient.reaction.reactionmeddrapt.exact:("CONFUSIONAL%20STATE")+AND+_exists_:(patient.reaction.reactionmeddrapt.exact)+AND+receiptdate:([1989-06-30+TO+2020-02-13])&limit=1&skip=0 ) 

Right now I have achieved to run the api but I cannot get results as it is shown in the following screenshot.
![image](https://user-images.githubusercontent.com/16148980/74418442-09165f00-4e51-11ea-86ae-82a30dca711a.png)

while the api that I run locally produces the following errors while running
![image](https://user-images.githubusercontent.com/16148980/74418608-4aa70a00-4e51-11ea-8a2b-015ee359f782.png)

Another question is if the right place to download the data is from here [https://open.fda.gov/downloads/](https://open.fda.gov/downloads/) 
I see there a lot of files and I don't see a file with the whole info.

for example
![image](https://user-images.githubusercontent.com/16148980/74418884-c30dcb00-4e51-11ea-80c6-83493edf7cf7.png)

From what I have understood, I should write code in order to retrieve the data using the following json file? 
[https://api.fda.gov/download.json](https://api.fda.gov/download.json)

Is there something ready for this?

**Comment by beckyconning** [comment]
I'm having this same problem. @dkrylovsb any ideas?

**Comment by evgakis** [comment]
@beckyconning maybe the files should be placed in a folder that should be declared in elasticsearch.yml
for example 
path.data: /etc/elasticsearch/data
But I get an error when running elasticsearch that seems to be from disk space requirements

`low disk watermark [85%] exceeded on [QUDv43gdRpSyCkmVh4XCsQ][Owl][/var/lib/elasticsearch/elasticsearch/nodes/0] free: 6.8gb[11.6%], replicas will not be assigne`

![image](https://user-images.githubusercontent.com/16148980/74447130-8a85e580-4e81-11ea-87d3-5b8c07ffa99f.png)


It does not seem to run even after freeing up some space

**Comment by beckyconning** [comment]
@evgakis did you ever work this out? i couldn't make heads or tails of it.

**Comment by evgakis** [comment]
Hi Becky!
No, I have let this the last month and I worked with other things.Nobody replies in this forum, so I don't know If I can work this out.
Where are you from? And where do you work?
Kind regards,Vagelis
    Στις Τετάρτη, 15 Απριλίου 2020, 02:51:08 μ.μ. EEST, ο χρήστης Becky Conning <notifications@github.com> έγραψε:  
 
 


@evgakis did you ever work this out? i couldn't make heads or tails of it.

**Comment by dkrylovsb** [comment]
The indexes in Elasticsearch are created and populated by running Python pipelines, source code for which is provided in this repository. The pipelines "know" how to obtain the data they need. However, running **all** pipelines is currently infeasible because many of the pipelines require data only available to FDA. Only _some_ pipelines can be run by the general public.

**Comment by dkrylovsb** [comment]
More information on how to run openFDA locally (select pipelines only) is here: https://github.com/FDA/openfda/pull/133
