### ISSUE TITLE
FAERs data falling behind again

### ISSUE THREAD

**Issue by JeremyHennessy** [FDA/openfda#120]
I previously left a issues a few months ago about the FAERs data (linked below), it was fixed and closed. It appears that the data is a few quarters behind the available data again. 

https://github.com/FDA/openfda/issues/113

**Comment by beardedfinch** [comment]
Hi @JeremyHennessy, I'm Jack with the openFDA Team. The temporary suspension of updates to the openFDA datasets has ended. We're in the process of updating all datasets. FAERS is still in the process of updating, but please stay tuned in to the [API Status page](https://open.fda.gov/about/status/) for update details. Thank you!
