### ISSUE TITLE
MAUDE frontend search vs API

### ISSUE THREAD

**Issue by kegwine** [FDA/openfda#122]
0

I am trying to use the openfda API to get a view of the data in the front end.

This is an example of a front end search: https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfMAUDE/detail.cfm?mdrfoi__id=2094110&pc=OCE

mdr_report_key: 2094110

this is the API query I'm trying:

https://api.fda.gov/device/event.json?search=mdr_report_key:%222094110%22&limit=30

Examples of data that is missing from the API:

1) Frontend - Brand Name: EPICEL (CULTURED EPIDERMAL AUTOGRAFTS) GRAFT

2) Frontend - Device Sequence Number : 1

3) Frontend - 1 Device Was Involved in the Event

Essentially any device or report data (description of event, I believe normally under mdr_text:[]) is missing from the search does not seem to show up in the API query, even though its the same mdr_report_key.

It looks like the front end joins together "Followups" to the "Initial Report" data. I was wondering how this is being joined on and how I can combine the data to something that makes sense? Should I ignore all Report_type: "follow up" records?

Thanks in advance!

**Comment by beardedfinch** [comment]
Answered on stackExchange - the issue was missing data in the source document.
