### ISSUE TITLE
Device Recall and Enforcement Update

### ISSUE THREAD

**Issue by JeremyHennessy** [FDA/openfda#123]
The API status of the Device Recall and Enforcement data states that it was updated this month, but there doesn't appear to be any recall events past December of 2019.

**Comment by beardedfinch** [comment]
Hi @JeremyHennessy, I'm Jack with the openFDA team. We received the updated Device Recall data last week and updated it on Saturday. The new data is now available:

[https://api.fda.gov/device/recall.json?search=event_date_terminated:[20200101+TO+20200420]&limit=100](https://api.fda.gov/device/recall.json?search=event_date_terminated:[20200101+TO+20200420]&limit=100)

Have a great day!

**Comment by JeremyHennessy** [comment]
Is this data not available in the Download section yet?
https://open.fda.gov/apis/device/enforcement/download/

**Comment by dkrylovsb** [comment]
Hi @JeremyHennessy , sorry about the confusion. The three "Enforcement Reports" datasets are indeed still in the process of being updated. We'll report back once that's done.

**Comment by dkrylovsb** [comment]
@JeremyHennessy This is now done.

**Comment by JeremyHennessy** [comment]
Thanks Denis, when will this info be added to the Downloadable files?

**Comment by dkrylovsb** [comment]
@JeremyHennessy The updates should be available in the Downloadable files as well.

**Comment by JeremyHennessy** [comment]
Perfect, thanks again Denis
