### ISSUE TITLE
Basic authorization headers result in CORS error

### ISSUE THREAD

**Issue by woodsjs** [FDA/openfda#131]
According to https://open.fda.gov/apis/authentication/, Basic auth is supported using https.

Sending a header with `Authorization: Basic <key>` results in a CORS policy error during preflight. Removing the header results in a successful response. Adding the api_key as a parameter to the request results in a successful response.

In looking at the server response, the server sends only the following 
`Access-Control-Allow-Headers: X-Requested-With
`
To successfully complete the CORS preflight, to use the Authentication header, I believe Authorization needs to be added to the Access-Control-Allow-Headers response.

**Comment by dkrylovsb** [comment]
Fixed.
