### ISSUE TITLE
drug adverse event schema bug

### ISSUE THREAD

**Issue by maksle** [FDA/openfda#139]
The schema says

```
"drugrecurrence": {
   "properties": {
       "drugrecuraction": {
            "type": "string"
        }
    }
}, ...
```

But the data looks like (see https://api.fda.gov/drug/event.json?search=safetyreportid:14340262&limit=1)

```
[{
  "drugrecuraction": "Urticaria"
},
 {
   "drugrecuraction": "Type III immune complex mediated reaction"
 },
 {
   "drugrecuraction": "Drug intolerance"
 },
 {
   "drugrecuraction": "Dyspnoea"
 }
],
```

The schema should say 
```
"drugrecurence": {
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "drugrecuraction": {
        "type": "string"
      }
    }
  }
}
```

EDIT -- The schema appears correct for some records: 
https://api.fda.gov/drug/event.json?search=safetyreportid:17394804&limit=1
So the data/schema is not consistent

**Comment by maksle** [comment]
The following keys are objects with a "properties" attribute but do not have a `{"type": "object"}` attribute in the schema:
`"summary", "patientdeath", "receiver", "reportduplicate"`

**Comment by maksle** [comment]
Also the `drug/event` schema is not in the xml returned at https://download.open.fda.gov/

**Comment by maksle** [comment]
`substance_name` in openfda should be declared as a list in the schema

**Comment by dkrylovsb** [comment]
Thank you for bringing these issues to our attention; they have been fixed. 

Please note that `https://download.open.fda.gov/` does bucket listing, which is limited by AWS to 1,000 elements, which is why the schema isn't in the list (it _is_ actually in the bucket)
