### ISSUE TITLE
Update/Create Documentation for Windows Users

### ISSUE THREAD

**Issue by joeld1** [FDA/openfda#140]
Could the documentation be updated for Windows users to clarify how to start the docker image on a Windows computer?

Windows users could be instructed to clone the repository as so

`git clone  https://github.com/FDA/openfda.git --config core.autocrlf=input `

In order to store the repository locally with Unix style line endings as specified in this [blog](https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/) in order to circumvent docker issues with building this image on a Windows computer.

**Comment by dkrylovsb** [comment]
Thank you for bringing this to our attention.
