### ISSUE TITLE
drug label missing field in schema

### ISSUE THREAD

**Issue by maksle** [FDA/openfda#142]
`adverse_reactions_table` is missing from the drug label dataset's schema and the fields yaml/pdf, but appears in the data.

**Comment by maksle** [comment]
`animal_pharmacology_and_or_toxicology_table` is missing in the schema as well, but is in the data. 
Example: https://api.fda.gov/drug/label.json?search=set_id:b244cda0-27f1-6708-c5df-916e7b53bd99

**Comment by maksle** [comment]
`abuse_table` is missing from the pdf/yaml

**Comment by maksle** [comment]
`veterinary_indications` is missing from the pdf/yaml but is in the schema

**Comment by dkrylovsb** [comment]
Fixed.
