### ISSUE TITLE
Is there a way to perform Wildcard queries?

### ISSUE THREAD

**Issue by justindra** [FDA/openfda#143]
I'm using the NDC endpoints and just trying to see if I can use a wildcard query? It looks like it is available in ElasticSearch, but when I pass it along it says that it isn't supported?

For example, 
```
https://api.fda.gov/drug/ndc.json?search=panad*&limit=25
```

Will return
```
Search not supported: panad*
```

**Comment by dkrylovsb** [comment]
Unfortunately, wildcard queries are not supported in openFDA API at this time.
