### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by maksle** [FDA/openfda#145]
There are records in druglabel with an `application_number` under the harmonized field `openfda.application_number` which are missing from the Drugs@FDA database. If I understand it right, Drugs@FDA is the go-to database to look up application_number.

For example, drug label with id `ab230fcf-2250-4224-81fd-17acbd246857` lists `openfda.application_number` `BLA103649`. However, that application_number is missing from the Drugs@FDA dataset.

If anything I said is incorrect, please let me know so that I improve my understanding, as well as who I may contact to enquire about this issue if you're not the ones to answer it.

Thanks!

**Comment by ldsopenfda** [comment]
Greetings,

            You have referenced a Biological Licensing Application (BLA) number in your message below.

            Drugs@FDA has information about BLAs which are approved by the FDA Center for Drug Evaluation and Research (CDER).

            Other BLAs which are approved by the FDA Center for Biologics Evaluation and Research (CBER) are in the FDA Purple Book<https://purplebooksearch.fda.gov/> which has information about CBER- and CDER-approved BLAs.


Thank you,

Lonnie Smith

**Comment by maksle** [comment]
Are there plans to add purple book and orange book to openfda?

**Comment by dkrylovsb** [comment]
Yes, although we are unable to provide a timeline at this time.
