### ISSUE TITLE
Objects in arrays are not well supported

### ISSUE THREAD

**Issue by Mariano215** [FDA/openfda#152]
Is there a way to avoid this?
Is there a fix or workaround?  
I would need to use these fields to search on.

![Objects In Arrays](https://user-images.githubusercontent.com/38673764/103233172-6355cc80-490a-11eb-86cd-c09c58749008.PNG)

**Comment by dkrylovsb** [comment]
I am not sure I fully understand the issue you are describing above. Would you please elaborate?

**Comment by Mariano215** [comment]
Actually - it's just a warning and I am able to utilize these fields for search.  I'll close this one.
