### ISSUE TITLE
High disk watermark

### ISSUE THREAD

**Issue by Mariano215** [FDA/openfda#153]
Is there a setting I can use to expand the disk space available?

es_1        | [2020-12-28T17:56:08,157][INFO ][o.e.c.r.a.DiskThresholdMonitor] [Eg-pbkY] rerouting shards: [high disk watermark exceeded on one or more nodes]
es_1        | [2020-12-28T17:56:38,184][WARN ][o.e.c.r.a.DiskThresholdMonitor] [Eg-pbkY] high disk watermark [90%] exceeded on [Eg-pbkYdQiqdNow_BOSdQA][Eg-pbkY][/usr/share/elasticsearch/data/nodes/0] free: 552.1mb[0.2%], shards will be relocated away from this node

**Comment by dkrylovsb** [comment]
It is possible that the host file system itself is running out of space thereby creating a low disk space condition for the Elasticsearch container. If this is not the case, however, please check to see if disk utilization may be is limited for Docker engine: https://docs.docker.com/docker-for-mac/space/

**Comment by Mariano215** [comment]
That link helped.  Thanks so much!
