### ISSUE TITLE
PMA Data Empty

### ISSUE THREAD

**Issue by Mariano215** [FDA/openfda#156]
![pmadata](https://user-images.githubusercontent.com/38673764/103446554-c7fd8800-4c78-11eb-83e3-124446a4d1d1.png)

Attaching docker logs.

[docker-log.tar.gz](https://github.com/FDA/openfda/files/5759466/docker-log.tar.gz)

**Comment by dkrylovsb** [comment]
openFDA does not create or use an index named `pmadata`. Perhaps you've made alterations to your local fork?
