### ISSUE TITLE
Adverse Events missing data files?

### ISSUE THREAD

**Issue by maksle** [FDA/openfda#157]
The latest data files under https://open.fda.gov/apis/drug/event/download/ are for 2020 Q3. However, there are results returned by the API for later dates (are the data file dates organized by quarter/year of the receivedate field?): 
https://api.fda.gov/drug/event.json?search=receivedate:[20201201+TO+20210208]&count=receivedate
If so, it appears they are missing from the download page (or are they buried under some of the "All other data" files perhaps?).

**Comment by dkrylovsb** [comment]
Yes, they were buried under the "All other" section. Thank you for alerting us; this is now fixed.
