### ISSUE TITLE
Device classification schema field missing.

### ISSUE THREAD

**Issue by castis** [FDA/openfda#160]
`summarymalfunctionreporting` is present in `device-classification.json` but not `deviceclass_schema.json`. 

Its possible the schema should include:

```
"summarymalfunctionreporting": {
  "type": "string"
},
```

**Comment by dkrylovsb** [comment]
`summary_malfunction_reporting` has been added to the Device Classification dataset.

Downloads schema: https://download.open.fda.gov/device/classification/deviceclass_schema.json
API: https://open.fda.gov/apis/device/classification/searchable-fields/
