### ISSUE TITLE
Device UDI schema missing type for openfda and sterilization

### ISSUE THREAD

**Issue by castis** [FDA/openfda#161]
Both [`properties.product_codes.items.properties.openfda`](https://github.com/FDA/openfda/blob/master/schemas/deviceudi_schema.json#L454) and [`properties.sterilization`](https://github.com/FDA/openfda/blob/master/schemas/deviceudi_schema.json#L698) do not specify a `type`, looks like they should both be `"type": "object"`

**Comment by dkrylovsb** [comment]
Fixed.
