### ISSUE TITLE
Prescription Frequency

### ISSUE THREAD

**Issue by FL33TW00D** [FDA/openfda#162]
Hi there,
First of all thanks for a brilliant API, nothing better than starting a new project and finding a fast well maintained API with the information you need.

I am attempting to analyse and compare the adverse events of different medications based on your adverse events API. However, I am running into the problem that I do not have the prescription frequency for these medications so cannot perform a direct comparison (since if a medication is prescribed 10x more than another its no. of adverse events will be 10x higher despite being no different in its negative effects). Is there any way to access this information through openFDA?

Many Thanks,
Chris

**Comment by dkrylovsb** [comment]
Unfortunately, prescription frequency information is not available in openFDA.
