### ISSUE TITLE
Is there a way to get manufacturer details and drug at the same time by using the single api?

### ISSUE THREAD

**Issue by mannusillegal** [FDA/openfda#169]

**Comment by dkrylovsb** [comment]
Yes, you can do that by using the Drug Label endpoint. Here is an example:

`https://api.fda.gov/drug/label.json?search=openfda.substance_name.exact:%22ASPIRIN%22&limit=10`

Look for the `manufacturer_name` field within the results. More details can be found [here](https://open.fda.gov/apis/drug/label/searchable-fields)
