### ISSUE TITLE
Only gets 1 unii / active ingredient from a drug label with multiple actives

### ISSUE THREAD

**Issue by tylerperyea** [FDA/openfda#17]
```
https://api.fda.gov/drug/event.json?search=patient.drug.openfda.pharm_class_epc:"nonsteroidal+anti-inflammatory+drug"&limit=1
```

The generic name is "ASPIRIN AND DIPYRIDAMOLE", which is for 2 uniis:
`64ALC7F90C` and `R16CO5Y76E` but only one of the UNIIs is returned. However, both preferred terms are returned:

```
{
    "unii": [
        "R16CO5Y76E"
    ],
    "substance_name": [
        "DIPYRIDAMOLE",
        "ASPIRIN"
    ]
}
```

Please add the unii for all preferred terms, as there will always be a 1-to-1 in SPL.

**Comment by cerdman** [comment]
Any update on this

**Comment by akcom** [comment]
I would like to know as well if there has been any progress here

**Comment by dkrylovsb** [comment]
Fixed: https://api.fda.gov/drug/event.json?search=patient.drug.openfda.pharm_class_epc:%22nonsteroidal+anti-inflammatory+drug%22+AND+patient.drug.openfda.generic_name:%22ASPIRIN%20AND%20DIPYRIDAMOLE%22&limit=1
