### ISSUE TITLE
MAUDE simple search in the openFDA API

### ISSUE THREAD

**Issue by carlosperezm** [FDA/openfda#170]
Hi all,
First of all, thanks for the wonderful tool provided here.

I am trying to replicate the simple search found in MAUDE with the API
https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/TextSearch.cfm

Unfortunately, I cannot find clear references of what it is precisely searching
The instructions only say:
> Enter a single word (e.g., electromechanical), an exact phrase (e.g., "electromechanical pump") in quotes or multiple words seperated by "and".

What is the equivalence in terms of the searchable fields here?
https://open.fda.gov/apis/device/event/searchable-fields/

Thanks a lot

**Comment by dkrylovsb** [comment]
Unfortunately, we do not have any insight into how exactly MAUDE simple search is implemented on the FDA website, so we are unable to determine an equivalence in terms of the openFDA searchable fields. You might want to consider the [Advanced Search](https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/Search.cfm) instead.

**Comment by carlosperezm** [comment]
ok, thanks for your reply!
