### ISSUE TITLE
Device - Adverse Events API Endpoint: "patient_problems" field missing from the results

### ISSUE THREAD

**Issue by NINEam-t** [FDA/openfda#173]
Hello,

I am no longer able to find the "**patient_problems**" field in the API call results.  It was previously within the "patient" field and is still described in the [data dictionary](https://open.fda.gov/data/datadictionary/) as patient.patient_problems but is missing from the actual returned results.

For example, Ctrl+F "patient_problems" returns 0 results for the following query:
https://api.fda.gov/device/event.json?search=device.device_report_product_code:(LPL+OR+LPN+OR+LPM)&limit=10

"patient": [
        {
          "patient_sequence_number": "1",
          "date_received": "20210802",
          "sequence_number_treatment": [
            ""
          ],
          "sequence_number_outcome": [
            "1. O"
          ]
        }
      ],

Thanks in advance for your help!

**Comment by dkrylovsb** [comment]
I have just tried the link you provided and can see at least 6 occurrences:
![image](https://user-images.githubusercontent.com/11096575/133476921-41701815-52d2-40d8-8c9f-16f4053540af.png)

**Comment by NINEam-t** [comment]
There were 0 just before I submitted this issue.  Perhaps this in the process of being corrected?

The field should exist for all returned records (10 in this case); the field should be populated with an empty array when there are not reported patient_problems.

**Comment by dkrylovsb** [comment]
No active corrections that we are aware of; `curl -gs "https://api.fda.gov/device/event.json?search=_exists_:patient.patient_problems" | grep total` reports over 10M matches, so everything seems to be in order. 

If we always include the field (even when there are no values), then we wouldn't be able to use `_exists_` and `_missing_` clauses against that field effectively, which could become an issue.
