### ISSUE TITLE
Device - Adverse Events API Endpoint: "patient_problems" data missing

### ISSUE THREAD

**Issue by NINEam-t** [FDA/openfda#174]
This is a follow up to Issue #173 which I believe was closed prematurely.

In addition to the patient_problems field name still missing from some records.  There is patient_problems _data_ missing as well.  See two examples from both openFDA and MAUDE:

**1a)** openFDA: https://api.fda.gov/device/event.json?search=report_number:%220001313525-2021-00110%22
![image](https://user-images.githubusercontent.com/41382313/133491691-5a1e7c83-6dd0-48e8-9bec-bae30e3e2fcc.png)

**1b)** MAUDE: https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/detail.cfm?mdrfoi__id=12362002&pc=LPL
![image](https://user-images.githubusercontent.com/41382313/133491380-700d1b05-9265-43db-92c5-4c73d4a63b1f.png)

**2a)** openFDA: https://api.fda.gov/device/event.json?search=report_number:%221057985-2021-00146%22
![image](https://user-images.githubusercontent.com/41382313/133491122-84547d43-39dd-4a92-9f1b-f61cc9af5589.png)

**2b)** MAUDE: https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/detail.cfm?mdrfoi__id=12318734&pc=LPM
![image](https://user-images.githubusercontent.com/41382313/133490961-fe4d7054-381b-4d62-a29f-c25d3afb7e57.png)

**Comment by dkrylovsb** [comment]
The problem has been identified and fixed. Thank you for bringing this to our attention.

**Comment by NINEam-t** [comment]
Thank you for the speedy resolution!
