### ISSUE TITLE
Foods › Adverse Events API data not updated

### ISSUE THREAD

**Issue by hendrik-hog** [FDA/openfda#177]
The Foods › Adverse Events API has not been updated in over a year. 
![image](https://user-images.githubusercontent.com/59823656/139005264-e5b32967-bcfb-42d6-bb00-bf70c491faea.png)
Is there a specific reason for this and can we expect the data to be updated again at some point?

**Comment by dkrylovsb** [comment]
Just a FYI: the FDA has updated the [CAERS data files](https://www.fda.gov/food/compliance-enforcement-food/cfsan-adverse-event-reporting-system-caers#files) on their website; that update has been applied in openFDA as well. 👍
