### ISSUE TITLE
Resolving URL for each device-recall via download.json api

### ISSUE THREAD

**Issue by grimuz** [FDA/openfda#178]
Hello, 

we are currently crawling the "download.json" API and process the "results.device.recall" section of this json-file to download all Device-Recall Data from OpenFDA.

This would be:
- https://download.open.fda.gov/device/recall/device-recall-0001-of-0001.json.zip

We would like to have (for each such downloaded Device-Recall) the corresponding URL of the Device-Event in den FDA accessdata web-interface.

For example: 
- https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfres/res.cfm?id=189471

But the downloaded Device-Recall Data does not contain this URL and also does not contain the "id" that would be needed to construct this URL on the fly.

The OpenFDA searchable fields does not list this URL or the "id" needed for the URL in the searchable fields. Also see:
- https://open.fda.gov/apis/device/recall/searchable-fields/

- Would it be possible for OpenFDA to return the Recall-URL in the future?
- Is there a way to construct the Recall-URL with the current results?

see also: https://opendata.stackexchange.com/questions/18149/how-do-i-get-the-url-for-a-specific-medical-device-recall-via-api

thanks in advance!

**Comment by dkrylovsb** [comment]
Yes, we will work on getting the `id` added to the Device Recall records and post back once done.  👍

**Comment by dkrylovsb** [comment]
A new field named `cfres_id` has been added to the Device Recalls dataset.
