### ISSUE TITLE
Device - Adverse Events API Endpoint: "patient" data missing for some records

### ISSUE THREAD

**Issue by NINEam-t** [FDA/openfda#179]
Hello,
I've noticed several records with an FDA received date from 1/7/2021 - 2/17/2021 that incorrectly have empty arrays for the patient data.  I've included two examples below.  (The patient problem data in the MAUDE screenshot comes from the patient data within each record, but it is missing from the openFDA json.)

1a) [openFDA](https://api.fda.gov/device/event.json?search=report_number:%221119421-2021-00042%22)
![image](https://user-images.githubusercontent.com/41382313/140072809-04de71cf-2ab6-4f86-a746-84a1ee6f39b4.png)

1b) [MAUDE](https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/detail.cfm?mdrfoi__id=11131671&pc=POE)
![image](https://user-images.githubusercontent.com/41382313/140073362-6f940e5e-1862-48d9-8c80-dcea39378bcc.png)

2a) [openFDA](https://api.fda.gov/device/event.json?search=report_number:%221119421-2021-00342%22)
![image](https://user-images.githubusercontent.com/41382313/140074492-d6c6b9d8-414e-4122-baa3-b49a73a2c0ff.png)

2b) [MAUDE](https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfmaude/detail.cfm?mdrfoi__id=11339476&pc=POE)
![image](https://user-images.githubusercontent.com/41382313/140074969-75715b1c-5167-4891-b74d-70fc516f53cd.png)

Could you please take a look at why this may have occurred?  Not all of the data from this date range has been affected.  Thanks in advance for your assistance!

**Comment by dkrylovsb** [comment]
Thank you for reporting this; we will investigate and get back with our findings.

**Comment by dkrylovsb** [comment]
This is now fixed.

**Comment by NINEam-t** [comment]
Thank you!
