### ISSUE TITLE
Definition of package descriptions

### ISSUE THREAD

**Issue by beckyconning** [FDA/openfda#181]
## Summary

Package descriptions that contain `*` don't seem to make sense.

### One

`2 KIT in 1 CARTON (50474-700-61)  > 1 KIT in 1 KIT *  1 mL in 1 VIAL, GLASS *  1 mL in 1 VIAL, GLASS`

The above seems to say that the package contains two kits and that each kit contains two 1ml vials (note that this doesn't say whether these vials contain the same or different drugs or strengths).

so we can break this up into

`2 KIT in 1 CARTON (50474-700-61)  > 1 KIT in 1 KIT > 1 mL in 1 VIAL, GLASS`

2 * 1 * 1 ml

and

`2 KIT in 1 CARTON (50474-700-61)  > 1 KIT in 1 KIT > 1 mL in 1 VIAL, GLASS`

2 * 1 * 1 = 2 ml

This seems correct

### Two

`24 BLISTER PACK in 1 CARTON (41226-627-24)  > 1 KIT in 1 BLISTER PACK *  2 BLISTER PACK in 1 CARTON > 4 CAPSULE, LIQUID FILLED in 1 BLISTER PACK *  16 CAPSULE, LIQUID FILLED in 1 BLISTER PACK`

However the above seems to say that there are twenty four kits (24 * 1) and that each kit contains a two blister packs of four capsules and one blister pack of sixteen capsules.

So we break that up like 

`24 BLISTER PACK in 1 CARTON (41226-627-24)  > 1 KIT in 1 BLISTER PACK > 2 BLISTER PACK in 1 CARTON > 4 CAPSULE, LIQUID FILLED in 1 BLISTER PACK`

24 * 1 * 2 * 4 = 192 capsules

and

`24 BLISTER PACK in 1 CARTON (41226-627-24)  > 1 KIT in 1 BLISTER PACK > 16 CAPSULE, LIQUID FILLED in 1 BLISTER PACK`

24 * 1 * 16 = 384 capsules

However i'm pretty sure that in reality this kit only contains 8 of one type of capsule and 16 of the other. So the initial 24 refers to the total number of capsules (not sure why thats relevant info as they are different drugs with different strengths).

## Conclusion and next steps

So how are we meant to make sense of this? Perhaps we could try ignoring everything in the first element (as split by `*` apart from the number of kits?

Is there some documentation somewhere? I can't seem to find it. It seems unfortunate as the ones that don't contain `*` tend to be quite clear and consistent even if they contain `>`.

**Comment by beckyconning** [comment]
These two seem at odds with each other.

`2 KIT in 1 CARTON (50474-700-61)  > 1 KIT in 1 KIT *  1 mL in 1 VIAL, GLASS *  1 mL in 1 VIAL, GLASS`

The above seems to say that the package contains two kits and that each kit contains two 1ml vials (note that this doesn't say whether these vials contain the same or different drugs or strengths).

so we can break this up into

`2 KIT in 1 CARTON (50474-700-61)  > 1 KIT in 1 KIT > 1 mL in 1 VIAL, GLASS`

2 * 1 * 1 ml

and

`2 KIT in 1 CARTON (50474-700-61)  > 1 KIT in 1 KIT > 1 mL in 1 VIAL, GLASS`

2 * 1 * 1 = 2 ml

This seems correct

`24 BLISTER PACK in 1 CARTON (41226-627-24)  > 1 KIT in 1 BLISTER PACK *  2 BLISTER PACK in 1 CARTON > 4 CAPSULE, LIQUID FILLED in 1 BLISTER PACK *  16 CAPSULE, LIQUID FILLED in 1 BLISTER PACK`

However the above seems to say that there are 24 kits (24 * 1) and that each kit contains both 2 blister packs of 4 capsules and 16 capsules.

So we break that up like 

`24 BLISTER PACK in 1 CARTON (41226-627-24)  > 1 KIT in 1 BLISTER PACK > 2 BLISTER PACK in 1 CARTON > 4 CAPSULE, LIQUID FILLED in 1 BLISTER PACK`

24 * 1 * 2 * 4 = 192 capsules

and

`24 BLISTER PACK in 1 CARTON (41226-627-24)  > 1 KIT in 1 BLISTER PACK > 16 CAPSULE, LIQUID FILLED in 1 BLISTER PACK`

24 * 1 * 16 = 384 capsules

However i'm pretty sure that in reality this kit only contains 8 of one type of capsule and 16 of the other. So the initial 24 refers to the total number of capsules (not sure why thats relevant info as they are different drugs with different strengths).

So how are we meant to make sense of this? Perhaps we could try ignoring everything in the first element (as split by `*` apart from the number of kits?

Is there some documentation somewhere? I can't seem to find it. It seems unfortunate as the ones that don't contain `*` tend to be quite clear and consistent even if they contain `>`.

**Comment by beckyconning** [comment]
```
24 BLISTER PACK in 1 CARTON (41226-627-24) > 1 KIT in 1 BLISTER PACK * 2 BLISTER PACK in 1 CARTON > 4 CAPSULE, LIQUID FILLED in 1 BLISTER PACK * 16 CAPSULE, LIQUID FILLED in 1 BLISTER PACK
```

The above and descriptions similar are certainly erroneous and I think we will have to live with it being wrong rather than trying to special case for it. We can't ignore the information prior to a split on ">" element with the word kit due to correct examples such as below.

```
10 CARTON in 1 CARTON (0944-5001-10)  > 1 KIT in 1 CARTON (0944-5001-01)  *  1 mL in 1 VIAL, GLASS (0944-5011-01)  *  1 mL in 1 SYRINGE, GLASS (0944-0011-01)
```

**Comment by beckyconning** [comment]
As an aside there are many kit package descriptions (i.e. `array_length(split(package_description,"*")) > 1`) which don't include NDCs on some or all of their kit components. This is quite useless as how can we tell what these quantities are referring to? 

Ok this kit contains 8 capsules and 16 capsules but which drugs are these?

I think it would be valuable for the NDC to have a clearer and more descriptive standard for kit package descriptions (i.e. `array_length(split(package_description,"*")) > 1`) and a stronger validation process for such applications.

**Comment by dkrylovsb** [comment]
Unfortunately, the openFDA Team does not maintain or manage the National Drug Code Directory -- we merely process the NDC downloadable files and expose the data via an API "as is". I think you have valid concerns, but this Github repo wouldn't be the best place to report them simply because it is not actively monitored by the FDA CDER team (i.e. the team that _actually_ manages the information in NDC). 

I would recommend emailing your concerns to this address -- edrls@fda.hhs.gov -- which can also be found on the https://www.fda.gov/drugs/electronic-drug-registration-and-listing-system-edrls/points-contact-drug-registration-and-listing page.

Sorry I could not be more helpful.

**Comment by beckyconning** [comment]
@dkrylovsb Thank you, this is very helpful. 

---

As a closing remark to help anyone else looking into this here is an explanation of my best guess of the meaning of such package descriptions.

When split by `*` the first element represents the kit quantity. Subsequent elements are things contained within the kit.

As such

2 KIT in 1 CARTON (50474-700-61) > 1 KIT in 1 KIT * 1 mL in 1 VIAL, GLASS * 1 mL in 1 VIAL, GLASS

The above seems to say that the package contains two kits and that each kit contains two 1ml vials (note that this doesn't say whether these vials contain the same or different drugs or strengths).

so we can break this up into

2 KIT in 1 CARTON (50474-700-61) > 1 KIT in 1 KIT > 1 mL in 1 VIAL, GLASS

total = 2 * 1 * 1 ml = 2ml

and

2 KIT in 1 CARTON (50474-700-61) > 1 KIT in 1 KIT > 1 mL in 1 VIAL, GLASS

total = 2 * 1 * 1 = 2 ml

See the above comments for other gotchas and concerns.
