### ISSUE TITLE
Request: Download Dataset of drug names

### ISSUE THREAD

**Issue by pradeepb28** [FDA/openfda#183]
It'd be great to provide a dataset to download all the drug names available on openFDA or atleast for the last few years.
With the downloaded set, I'd like to roll my own
- Fuzzy search engine
- ML analysis
- Better experience on the frontend

Thank you!

**Comment by dkrylovsb** [comment]
Hi there, thanks for reaching out! This information is already readily available in downloadable form on our Downloads [page](https://open.fda.gov/data/downloads/). The dataset you'd want is Drug Labeling: has nearly 200K drug records going all the way back. You would have parse JSON and extract the fields you need though.

Unfortunately, we are unable to provide the exact dataset you are requesting as it would be too specific and serve a narrow set of use cases. Sorry about the inconvenience.
