### ISSUE TITLE
Find drugs based on health condition

### ISSUE THREAD

**Issue by pradeepb28** [FDA/openfda#184]
It seems to be straightforward to find information about drug details based on drug name. I am also looking for drug suggestions based on medical condition.

For example: I want to know medication suggestions for condition like for Fever, headache.

Is it possible to do with openFDA API?

**Comment by dkrylovsb** [comment]
You can try searching within the `indications_and_usage` section of Drug Labels, such as

[https://api.fda.gov/drug/label.json?search=indications_and_usage:fever](https://api.fda.gov/drug/label.json?search=indications_and_usage:fever)

However, please be advised that any results returned do not constitute a medical advice. Do not rely on openFDA to make decisions regarding medical care and always speak to your health provider about the risks and benefits of FDA-regulated products.

**Comment by pradeepb28** [comment]
Thank you @dkrylovsb but it seems like it doesn't return brand name or generic name of the drug 🤔 . Is there a way to get those information too?

**Comment by dkrylovsb** [comment]
Yes, we can further modify the query to require the `openfda` section as follows:

https://api.fda.gov/drug/label.json?search=indications_and_usage:fever+AND+_exists_:openfda

Many old/discontinued drugs will not have the `openfda` section.
