### ISSUE TITLE
Device Events Endpoint - May 2022 data not yet available via API

### ISSUE THREAD

**Issue by NINEam-t** [FDA/openfda#188]
Hello,
I've noticed that the MAUDE data for May 2022 is not yet available using the API although the database says it was updated July 5, 2022.  I have not seen it lag this far behind before.  Do you know when the May (and June) data will be available?
Thanks and best regards!

**Comment by sunnyseattle98008** [comment]
^ what he/she says above; I'm also seeing an issue with the device endpoint.  It stops working for searches beyond 4/30.   Please let us know.

**Comment by dkrylovsb** [comment]
This has been fixed.
