### ISSUE TITLE
API not showing 2/22/2023 class II recalls

### ISSUE THREAD

**Issue by al2882** [FDA/openfda#193]
This recall happened on Feb. 22, 2023:
https://www.accessdata.fda.gov/scripts/ires/index.cfm?Product=198118

Today is Feb. 24, 2023 and the results do not show on the API:
`https://api.fda.gov/drug/enforcement.json?search=product_type:%22Drugs%22+AND+classification:%22Class+II%22+AND+report_date:[2023-02-20+TO+2023-12-31]&limit=1000`

Can you check if the API is refreshing correctly? 

Thanks.

**Comment by dkrylovsb** [comment]
The recall in question now appears within the results.
