### ISSUE TITLE
Does the API support Spanish language?

### ISSUE THREAD

**Issue by derian-all-win-software** [FDA/openfda#194]
According to this example `https://api.fda.gov/drug/label.json?search=active_ingredient:aspirin&lang=es` the query contains a `lang` parameter which is given the value of `es`, when the request is made it returns the following error:
 
```json
{
  "error": {
    "code": "BAD_REQUEST",
    "message": "Invalid parameter: lang"
  }
}
```

Is the `Spanish` language still supported when making a request?

**Comment by dkrylovsb** [comment]
No, openFDA does not support languages other than English.
