### ISSUE TITLE
Drug Labeling API Search

### ISSUE THREAD

**Issue by joelmontavon** [FDA/openfda#197]
I am performing a search with the Drug Labeling API via this URL: https://api.fda.gov/drug/label.json?search=openfda.package_ndc:72611-772-01. The results include labels for products that are not for the appropriate NDC.

**Comment by dkrylovsb** [comment]
Hi @joelmontavon,

Please use the `exact` version of this field to get _only_ exact matches as follows:

https://api.fda.gov/drug/label.json?search=openfda.package_ndc.exact:72611-772-01
