### ISSUE TITLE
Need instructions for getting up and running

### ISSUE THREAD

**Issue by marks** [FDA/openfda#20]
Love that this is all open source but there aren't any instructions (that I can find) to get up and running. 

I ran `bootstrap.sh` and `run_faers_pipeline.sh` but the second doesn't complete successfully.  Log of running `run_faers_pipeline.sh` again: https://gist.github.com/marks/a7d50c46a78f85b0ac1a . This is using master from yesterday afternoon.

Thanks,

Mark

**Comment by mattmo** [comment]
Please feel free to open a new issue if this is still a problem. Thanks!
