### ISSUE TITLE
Please add support for partial search

### ISSUE THREAD

**Issue by MyLifeHealthApp** [FDA/openfda#201]
I read that you took the path against ngram approach for tokenization of your API.  We would love you to reconsider so that we do not have to download all of the medication data for our app.  It is hard for an end user to type out the entire prescription name in a search so partial search is hugely important to us. If you would open that up it would make consumers like us (MyLifeHealth) very happy to not have to support all that extra code and frequent downloads from you.

We appreciate you giving us a voice here!  Love that you are maintaining this!  =)

Appreciatively,
MyLifeHealth Development Team

**Comment by dkrylovsb** [comment]
Done: https://open.fda.gov/apis/wildcard-search/
