### ISSUE TITLE
Delay in openFDA's drug recalls/enforcement reports

### ISSUE THREAD

**Issue by rsinger86** [FDA/openfda#24]
It looks like there is a delay in the data served by the openFDA's enforcement report API. Right now, the most recent records in the responses from the endpoint are dated 6/18, but the most recent enforcement report from the FDA was released 7/16: http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=07162014&lang=eng

Are there plans to close this gap in the future?

**Comment by rajdipp** [comment]
I see that on the FDA adverse events reporting (FAERS) public dashboard the data is already as of June 30, 2018 whereas on the API its still as of March 31, 2018.

So, it seems that there is a lag between when the quarterly files are posted to FAERS/public dashboard and when the openFDA API is updated. Do you know what is the typical/expected lag?

https://api.fda.gov/drug/event.json?search=receivedate:20180101+TO+20180813&count=receivedate

{ "time": "20180329", "count": 288 }, { "time": "20180330", "count": 237 }, { "time": "20180331", "count": 20 } ] }

**Comment by dkrylovsb** [comment]
We'll update next week.

**Comment by CalebYates1** [comment]
I can see this is a common problem of the past but what is the time schedule for updates currently and into the future? As of September 26th, 2018 the information for the enforcement information is only up to July 12th of 2018. Also the recall database is not up to date either. Is there an expected update schedule we can come to rely on?
