### ISSUE TITLE
Where is the “product problem” field in the device AE endpoint?

### ISSUE THREAD

**Issue by marks** [FDA/openfda#27]
Please see full question by @GeekNurse and I on SE at https://opendata.stackexchange.com/questions/3543/where-is-the-product-problem-field-in-the-openfda-api

> In the MAUDE search tool on FDA.gov there is a standard list of problems in a product problem field. This is not available in the API.

For example: 

> compare http://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfMAUDE/detail.cfm?mdrfoi__id=1693964 where there is a "Device Problem" of "Absorption" to the same record from the openFDA API: https://api.fda.gov/device/event.json?search=BM2HCPM0

**Comment by ILuggiI** [comment]
There hasn't been any updates about 4 years. Is this issue still active?

**Comment by dkrylovsb** [comment]
We are working on fixing this.

**Comment by dkrylovsb** [comment]
A new field -- `product_problems` is now available via the API; see https://api.fda.gov/device/event.json?search=mdr_report_key:1693964 for an example. We'll follow up with a website update shortly as well. Sorry about the long wait.

**Comment by maksle** [comment]
This is in the API but doesn't appear in the fields documentation.

**Comment by dkrylovsb** [comment]
Thank you for alerting us; we've queued work to address this.
