### ISSUE TITLE
Labels API, improve formatting of result.dosage_and_administration

### ISSUE THREAD

**Issue by Kuzmin** [FDA/openfda#33]
In the XML files there's formatting that states pretty clearly which part of the text that is headers and what relates to dosage/administration. In the JSON files, all this formatting has been removed to form texts like `['Directions Apply liberally and evenly 15 minutes before sun exposure. Reapply at least every 2 years Use a water resistant sunscreen if swimming or sweating. Children under 6 months of age: Ask a doctor.']`
or `['Dosage and Administration: Take up about 1.2g - 1.5g of it and smooth over the entire face.']`.

With access to the xml files you can see that the first example could pretty easily be split up into 
    `['Apply liberally and evenly 15 minutes before sun exposure. Reapply at least every 2 years.',
    'Use a water resistant sunscreen if swimming or sweating.', 
    'Children under 6 months of age: Ask a doctor.']`

And it would be magnitudes easier to do some kind of language processing on this data.

**Comment by Shane-Neeley** [comment]
I just closed my duplicate issue on the subject. But yes I would find it extremely helpful of all of the paragraph formatting from the SPL XMLs was translated into \n new lines, or <br>, or even an array like suggested above.

**Comment by RxData** [comment]
This would also be very helpful for us if the data in Indications_and_Usage were broken up like the <paragraphs> or other tags in the SPL XML.  We would like to be able to cleanly separate multiple different indications into their own snippets of text out of the whole label indications section, so if bullet point lists, or 1.1, 1.2, ,.. etc subsections could have some standard delimiters or tags, that would be helpful. We are only interested in Rx drugs, not OTC.
