### ISSUE TITLE
What's namespace should we use for drug classes

### ISSUE THREAD

**Issue by ningyifan** [FDA/openfda#37]
I am Yifan Ning, a programmer in DBMI, University of Pittsburgh.  I am working on create mappings in active moiety RDF graph.

Woud you please provides me advice about namespace for drug classes? Such as Mechanism of action (MoA), Physiologic effect(PE) and Established pharmacologic class (EPC). I find documentation for drug classes here "https://open.fda.gov/api/reference/#spl" but there are no namespaces provides.

Appreciate for your any help.

Best wishes,
Yifan

**Comment by sgtp** [comment]
Was there any followup on the idea of representing openfda in RDF ?
