### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by westurner** [FDA/openfda#43]
* https://www.python.org/dev/peps/pep-0008/ (4 spaces per tab)
* https://google-styleguide.googlecode.com/svn/trunk/pyguide.html#Indentation (4 spaces per tab)
* https://github.com/Khan/style-guides/blob/master/style/python.md#indentation (4 spaces per tab)

> This is a strict rule and ignoring this can (has) cause(d) bugs.

* https://github.com/spulec/pep8ify
* https://github.com/rubik/radon

**Comment by westurner** [comment]
* https://github.com/FDA/openfda/blob/master/.editorconfig
* https://github.com/editorconfig/editorconfig-vim

**Comment by rjpower** [comment]
This project follows an older version of the Google Python style, which diverges slightly from the current Google style (in particular with respect to spacing).
