### ISSUE TITLE
Dockerfile for testing

### ISSUE THREAD

**Issue by westurner** [FDA/openfda#45]
For testing, it would be helpful to add a ``Dockerfile`` for Docker.

https://docs.docker.com/reference/builder/

Examples that could be merged / extended ``FROM``:

* https://github.com/dockerfile/elasticsearch/blob/master/Dockerfile
* https://github.com/dockerfile/supervisor/blob/master/Dockerfile
* https://github.com/dockerfile/python/blob/master/Dockerfile
* https://github.com/dockerfile/nodejs-bower-grunt/blob/master/Dockerfile
  * https://github.com/dockerfile/nodejs/blob/master/Dockerfile

**Comment by westurner** [comment]
It may then be helpful to retrieve the datasets before pushing the image.

**Comment by marks** [comment]
+1 - for testing by openFDA team *and* to allow community to spin up their own instances

**Comment by GeekNurse** [comment]
Another +1

On Jan 31, 2015, at 2:52 PM, Mark Silverberg <notifications@github.com<mailto:notifications@github.com>> wrote:


+1 - for testing by openFDA team and to allow community to spin up their own instances

-

**Comment by HansNelsen** [comment]
We are about to do a pretty big push (not sure on the exact ETA, but pretty soon). We have a Dockerfile for the api code and for Elasticsearch.

**Comment by westurner** [comment]
Awesome, thanks!

**Comment by HansNelsen** [comment]
FYI: The latest push happened today.

**Comment by westurner** [comment]
I see https://github.com/FDA/openfda/tree/master/deploy/docker

Is there a Dockerfile in the root of the repository (e.g. for reference as https://registry.hub.docker.com/repos/fda/openfda)?

**Comment by rjpower** [comment]
There isn't one Dockerfile that fits the whole project; one is provided for the elasticsearch workers and one for the nodejs API server.

**Comment by westurner** [comment]
* https://github.com/FDA/openfda/blob/master/api/faers/Dockerfile
* https://github.com/FDA/openfda/blob/master/deploy/docker/elasticsearch/Dockerfile

Thanks again!
