### ISSUE TITLE
Drug Label API code to be added?

### ISSUE THREAD

**Issue by RxData** [FDA/openfda#47]
Will the code be added which powers the "api.fda.gov/drug/<b>label</b>.json" end point?

**Comment by HansNelsen** [comment]
We are about to do a pretty big push. The incremental loader for the label index and the api code will both be in there. I do not have an exact ETA on the push, but it should be relatively soon.

**Comment by rjpower** [comment]
The pipeline that produces the label endpoint is available in the `openfda/spl` directory.
