### ISSUE TITLE
ENH: Adverse Event Count / 'Use' Count Heatmap

### ISSUE THREAD

**Issue by westurner** [FDA/openfda#49]
- [ ] A matrix with rows listing treatments, and columns listing adverse event types (# of events)
  - [ ] Shade each cell w/ a log-scale
  - [ ] All treatments would require high resolution (but might be cool)
  - [ ] A select number of treatment alternatives could be immensely useful
- [ ] Where can we find Prescription Counts (or OTC Sales Numbers)?
  - [edit]
    - **denominators** for relative risk statistic comparisons
      - manufacturing count
      - sales count
      - usage count

I feel that such charts could represent the primary interests of Public Health in the United States.

**Comment by westurner** [comment]
@beardedfinch
Why did you close this issue?

**Comment by beardedfinch** [comment]
Hi Wes,

Like the other issue, this was several years old so I was closing it as part of routine clean-up. If this is still relevant let me know and we'll take a look.

**Comment by westurner** [comment]
Do we have a denominator statistic that we could use to compare the
frequencies? AFAIU, AERS has raw event counts (that we can use a population
statistic as a denominator with in order to get an incidence rate (per
100,000 people).

But if we have 1000 reported events for treatments A and B, we have no idea
whether they're of equal hazard without sales numbers or usage estimates.

1000 / 1000 != 1000 / 1000000

Is there another FDA system with combined sales counts and/or usage
estimates for active ingredients?

With that information, we could shade cells in a heat map (and estimate
relative hazard) using this so useful post-market adverse event report data
as a numerator.

On Monday, October 7, 2019, Jack Finch <notifications@github.com> wrote:
> Hi Wes,
>
> Like the other issue, this was several years old so I was closing it as
part of routine clean-up. If this is still relevant let me know and we'll
take a look.
