### ISSUE TITLE
Drug label mismatch - Helixate FS

### ISSUE THREAD

**Issue by akcom** [FDA/openfda#52]
When running a query against “Helixate FS” as such: https://api.fda.gov/drug/label.json?search=brand_name:Helixate%20FS&limit=1
The result returned is for the wrong drug (returned: ‘Doxirubicin’).  In addition, the ‘openfda’ field is nil.

**Comment by akcom** [comment]
Another instance of the wrong information being provided:
https://api.fda.gov/drug/label.json?search=brand_name:Botox+Cosmetic

returns the information for isotretinoin

**Comment by HansNelsen** [comment]
You are correct about the quote marks needing to be included. For thoroughness, I would also add the prefix `search=openfda.brand_name:"Botox+Cosmetic"`. If you want to do do an exact match, then add the `.exact` extension to the key name.   `search=openfda.brand_name.exact:"Botox+Cosmetic"`

There is a reference in the documentation to needing quote marks for these types of queries here:
https://open.fda.gov/api/reference/

Please let us know if you have any other questions. Thanks for using the openFDA!

**Comment by akcom** [comment]
Excellent, thank you for the information!
