### ISSUE TITLE
Drug label - drugs missing

### ISSUE THREAD

**Issue by akcom** [FDA/openfda#53]
I’m interested in pulling FDA labeling information for various oncology specialty pharmacy products.  I’ve noticed that a small but significant number of products do not have labeling information available (they yield an error: NOT FOUND, “No matches found!”) .  I’ve attached a sample of drugs (brand name & generic) for which I was unable to pull the labeling. I was just hoping you could provide some insight on what’s going wrong, whether it’s an error in my query or the information just isn’t there yet.  For all of the drugs in the list, I’ve tried querying with both the brand name, ex:
https://api.fda.gov/drug/label.json?search=brand_name:Zarxio
and the generic name, ex:
https://api.fda.gov/drug/label.json?search=generic_name:Pegfilgrastim

![image](https://cloud.githubusercontent.com/assets/405482/8186147/8fe3955e-1416-11e5-8f3c-680daca99fb1.png)

**Comment by akcom** [comment]
Ruconest
Humira
Novantrone
Glassia
Zemaira
Oralair
Aranesp
Neulasta
Gilotrif
Prothelial
Zoladex
Skyla
Kalydeco
Advate
Alphanate
Alprolix
Benefix
Corifact
Eloctate
Helixate FS
Koate-DVI
Kogenate FS
Mononine
Novoseven RT
RiaSTAP
Rixubis
Tretten
Wilate
Xyntha
Pegasys
Berinert
Cinryze
Tybost
Viramune XR
Bivigam
Cytogam
Flebogamma
Gammaked
Gammaplex
Hizentra
Hyqvia
Privigen
progesterone injection
Arcalyst
Arestin
Kynamro
Solesta
Rebif
Lucentis
Euflexxa
Hyalgan
Monovisc
Orthovisc
Supartz
Synvisc
Prolia
Adcirca
Letairis
Opsumit
Liletta
Feiba vh
Helixate fs
Koate-dvi
Kogenate fs
Novoeight
Novoseven
Obizur
Refacto
Riastap
Ribatab
Evotaz
Prezcobix
Vitekta
Viadur
Continued
Gammagard
Gamunex
Micrhogam
Rhogam
Rhophylac
Varizig
Lemtrada
Blincyto
Elspar
Opdivo
Farydak
Ibrance
Mugard
Amevive
Cosentyx
Rasuvo
Esbriet
Iluvien

**Comment by HansNelsen** [comment]
Thank you for posting this thorough list. I will dig into and see what is happening. 

The few that I have looked at so far are due to an empty `openfda` which can happen for a number of reasons, so I will dig into it to see why they are missing (missing is not always an error).

As such, the reason you are not getting hits, is that the `brand_name` falls under the `openfda`. The labels are there, but you will get a less precise search if you just search for `search=Zarxio`, meaning that you would have to programmatically verify that it was the drug for which you are looking, with something like a `set_id`.

Thanks for point this out. I will post back here with what I find. Thanks for using the openFDA!

**Comment by akcom** [comment]
@HansNelsen 
Thank you again for your help.  Just an FYI, there are some that do not show up even using the simple 'search=name' syntax. Ex: Oralair, Humira, Glassia, Eloctate

Some of the drugs in my list are blood products though, which explains why they are not showing up.  From those that I've taken a cursory look at, it seems like they are all biologic therapies.  I do not know if this applies to the entire list though.  Hope this helps!

**Comment by HansNelsen** [comment]
Hmm. I was able to get Humira to show up. You might need to increase the limit, since it is a broader search, you may get some extra hits (for instance, the real Humira is on the second result).

HTH. I will get back to you on what I find.

**Comment by RxData** [comment]
Alex,

As Hans said, Humira and the other drugs are missing their open_fda
sections which contain the brand_name and generic name fields.  You can get
to the Humira label at
https://api.fda.gov/drug/label.json?search=humira&skip=3
<https://api.fda.gov/drug/label.json?search=humira&skip=3&limit=1>.  There
are a total of 10 labels that include the word "Humira".  The label API
will only return one label at a time though, so you need to use the
skip=... parameter to select which of the results to view.

-Joe

On Tue, Jun 16, 2015 at 1:52 PM, Hans Nelsen <notifications@github.com>
wrote:

> Hmm. I was able to get Humira to show up. You might need to increase the
> limit, since it is a broader search, you may get some extra hits (for
> instance, the real Humira is on the second result).
>
> HTH. I will get back to you on what I find.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FDA/openfda/issues/53#issuecomment-112512648>.
>



-- 
Joe Segal

Co-Founder & CTO
*RxData, Inc.*
447 Broadway, 2nd Floor
New York, NY 10013
phone: +1 (321) 356-6305
jsegal@rxdata.net | rxdata.net

**Comment by akcom** [comment]
@RxData thank you for the help!

**Comment by HansNelsen** [comment]
Something you can use to make you processing a bit easier:

`search=_missing_:openfda.brand_name` will return the labels that do not have openfda sections populated. ``search=_exists_:openfda.brand_name` will tell you if they do.

**Comment by akcom** [comment]
@HansNelsen any update on why certain drugs do not contain a populated openfda field?  Thanks!

**Comment by dkrylovsb** [comment]
Certain drugs may be missing `openfda` section if there is a mismatch between SPL IDs in SPL file _and_ NDC dataset for those drugs.
