### ISSUE TITLE
Add a sort by parameter

### ISSUE THREAD

**Issue by dmfenton** [FDA/openfda#54]
As a user, I want to query for the 10 most recently initiated food recalls without any other parameters.

**Comment by poorgeek** [comment]
:+1:

**Comment by acouch** [comment]
:+1:

**Comment by SerhiiS-in6k** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by dkrylovsb** [comment]
OK, we are working on this.

**Comment by dkrylovsb** [comment]
Done. New `sort` query parameter can now be used to specify a field to sort on with optional `:asc` or `:desc` modifiers. The field must be either a date field or an "exact" field. This API change is already live with a website update to follow shortly.

@dmfenton The query you originally referred to would translate into https://api.fda.gov/food/enforcement.json?sort=report_date:desc&limit=10. 

Sorry about the long wait, all.
