### ISSUE TITLE
Serve exports of the data or allow a skip parameter greater than 5000

### ISSUE THREAD

**Issue by dmfenton** [FDA/openfda#55]
As a user, I want to gather all the data so I can enrich it and bring it into a tool of my choosing.

**Comment by marks** [comment]
There should actually be an issue for this already by yours truly... I'll link to it when I can 


--
Mark Silverberg
(m) 512 826 7004
http://twitter.com/skram

**Comment by mattmo** [comment]
Thanks for reporting. As @marks indicates, this has been a popular request and the team has noted this. Will update this bug when I can share more.

**Comment by dmfenton** [comment]
So at least for the food recalls API I've set this up here:
- [CSV](http://koop-fda-1504637322.us-east-1.elb.amazonaws.com/FDA.csv)
- [Shapefile](http://koop-fda-1504637322.us-east-1.elb.amazonaws.com/FDA.zip)
- [KML](http://koop-fda-1504637322.us-east-1.elb.amazonaws.com/FDA.kml)
- [GeoJSON](koop-fda-1504637322.us-east-1.elb.amazonaws.com/FDA.geojson)

If you are interested, the Open Source tools behind this are:
- https://github.com/Esri/koop
- https://github.com/koopjs/koop-fda

**Comment by mattmo** [comment]
Downloads are now available on the website. Please open another issue if this format is not adequate for your needs. Thanks!
