### ISSUE TITLE
Server error returned on invalid date search

### ISSUE THREAD

**Issue by dmfenton** [FDA/openfda#56]
``` bash
curl -XGET 'https://api.fda.gov/food/enforcement.json?limit=1&search=report_date:[2000-10-01+TO+2013-09-31]'
```

``` json
{
  "error": {
    "code": "SERVER_ERROR",
    "message": "Check your request and try again"
  }
}
```

Probably better to return a more helpful response.

**Comment by mattmo** [comment]
Thanks for flagging. We had looked into this last year but it was difficult to get better error messages back from Elasticsearch at that time. We will revisit this as Elastic has changed quite a bit since then.

**Comment by dkrylovsb** [comment]
Fixed.
