### ISSUE TITLE
Don't return 404 on request with no results

### ISSUE THREAD

**Issue by dmfenton** [FDA/openfda#58]
404 is a confusing response here. I've hit the right endpoint and my parameters are valid. It's OK that there are no results. I suggest that you send along the regular response with an empty result set rather than sending a status code that indicates I made a mistake.

``` bash
https://api.fda.gov/food/enforcement.json?search=report_date:[2015-06-01+TO+2016-03-31]&limit=0
```

``` json
{
  "error": {
    "code": "NOT_FOUND",
    "message": "No matches found!"
  }
}
```

**Comment by mattmo** [comment]
In my experience, this is a pretty common way to handle no results found for REST APIs and by now there are several clients that depend on this behavior. That said, I do think we could do a better job documenting this. Where would you expect this to be documented on the site? Do you think this would have helped you avoid this confusion?

**Comment by dmfenton** [comment]
Debatable. You guys expose the fact that this is Elasticsearch backed so you should have a strong for any deviation. That deviation is the cause of surprise and I don't think documenting this somewhere is going to fix that. Here is the direct result from Elasticsearch on a zero result search.

```bash
curl -XGET 'localhost:9200/koop/_search?q=agrabar' --ipv4 -i                                                               [7:42:01]
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 122

{"took":7,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}%
```

**Comment by harjitdotsingh** [comment]
I think when there are no results. the results key should return 0. If we are using 404 that can mean lot os things because if I have a bad URL that also returns me 404. How would you differentiate between a bad request and 404 results not returned ?

**Comment by acouch** [comment]
I would agree that the 404 for no results behavior is confusing.

**Comment by dkrylovsb** [comment]
Agreed with the criticism of the 404, but changing it to a no-results response at this point may break clients. Introducing a new version of the API solely for this reason is probably too much, either. We'll probably just have to live with that, at least for a while.
