### ISSUE TITLE
Cannot load Recall Details with an ID

### ISSUE THREAD

**Issue by harjitdotsingh** [FDA/openfda#59]
Hi there,

Need an endpoint which actually gives out more details regarding a request when an ID is passed. Right now there is none.

**Comment by marks** [comment]
Take a look at this StackOverflow question: http://opendata.stackexchange.com/questions/5505/return-an-enforcement-record-for-search-recall-number/5509#5509

**Comment by mattmo** [comment]
Thanks @marks. @harjitdotsingh - did that answer your question?

**Comment by harjitdotsingh** [comment]
That worked... Thanks
