### ISSUE TITLE
How to get a review page link or review files for  a certain drug using API?

### ISSUE THREAD

**Issue by meihanred** [FDA/openfda#61]
I wanna get the review link for a certain drug links via API, e.g, for the drug "AUBAGIO", it's

"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm?fuseaction=Search.Set_Current_Drug&ApplNo=202992&DrugName=AUBAGIO&ActiveIngred=TERIFLUNOMIDE&SponsorApplicant=SANOFI%20AVENTIS%20US&ProductMktStatus=1&goto=Search.Label_ApprovalHistory"

And that can be access by search "Abagio", then within the drug page, click on the "Approval History, Letters, Reviews, and Related Documents".

That link refers to the review link I need. So is there any possible way to obtain that using API or programmatically? If there is no way to do that, how I can obtain the review pdf files or file link for each certain drugs? Coz I'm going to fetch the review pdf files for each drugs approved in a certain year. I am thinking that first I can locate a unique link for each drug, and then to get the review files, which are just on the page, is not hard. Or if there is a way that can directly locate the review files would be better.

Thank you!

**Comment by mattmo** [comment]
Thanks for filing this. Unfortunately, our APIs do not currently include the Drugs@FDA datasets. I'll file a request with the team about this.
