### ISSUE TITLE
Adverse Event Case Sensitivity

### ISSUE THREAD

**Issue by Luke-Malchow-Bergenthal** [FDA/openfda#62]
Most MedDRA preferred terms are in all capital letters, however some are given a title case (as is noted, this is due to differences between AERS and FAERS). This causes problems when querying for counts of exact reactions. Take for instance the following example: 

https://api.fda.gov/drug/event.json?search=patient.drug.openfda.generic_name:"ACETAMINOPHEN"&count=patient.reaction.reactionmeddrapt.exact

Here there are two separate counts for pain, "PAIN" at 5997 occurrences and "Pain" at 3769 occurrences.

I am not very well versed when it comes to elasticsearch, but as far as I can tell the custom analyzer "uppercase_not_tokenized" looks like it is written correctly.

**Comment by rjpower** [comment]
Thanks for noticing this.  This was a bug that was introduced during a recent pipeline update, and has now been fixed.

**Comment by Luke-Malchow-Bergenthal** [comment]
Thank you! Your work is very much appreciated.
