### ISSUE TITLE
Inconsistent fields

### ISSUE THREAD

**Issue by javydreamercsw** [FDA/openfda#63]
This question is related to http://stackoverflow.com/questions/32363315/gson-fields-that-sometimes-are-strings-and-others-arrays and http://opendata.stackexchange.com/questions/5926/inconsistent-fields

I'm parsing json with Gson but I'm struggling with the data I'm getting. This is part of an API out of my control (openFDA) so changing that might not be an option.

Here's the json I'm strugling with: [https://api.fda.gov/device/event.json?search=device.generic_name:generator&limit=10](https://api.fda.gov/device/event.json?search=device.generic_name:generator&limit=10)

There are some fields that are not consistent, for example remedial_action. Sometimes it comes out like this:

```
"remedial_action": [
        "Recall"
]
```

and in other results like this:

```
"remedial_action": ""
```

So it's either an array or a plain string. Looks like a bug to me. But I'm a json newbie.

**Comment by HansNelsen** [comment]
Thanks! It is definitely a bug. I will take a look at the pipeline to see where it is happening. This particular pipeline is scheduled for a refactor to be more inline with the map/reduce approach we now use. I do not have an ETA at this point however. I will ping back here when I do. Thanks again.
