### ISSUE TITLE
Docker deployments not working without modification

### ISSUE THREAD

**Issue by cerdman** [FDA/openfda#66]
Would be helpful to have these reference either a yaml config file for things like EC2 security groups, aws keys, and git repos, which are currently hardcoded into the deploy scripts.

For instance
https://github.com/FDA/openfda/blob/master/deploy/docker/dev-setup.sh

Has a call to:
```git clone git@github.com:iodine/openfda-internal```

**Comment by HansNelsen** [comment]
This has been fixed.
