### ISSUE TITLE
NotFilter (boolean 'not' queries)

### ISSUE THREAD

**Issue by phiat** [FDA/openfda#7]
Can we add a way to boolean (not) a query?  elastic.js uses a NotFilter.  
Maybe use '!' for boolean NOT.  Is there a way to currently do this? (ex: return all events where patient.drug.openfda.manufacturer_name != 'ABC company').

**Comment by plasmite** [comment]
To build on this--can I filter requests to not include entire fields altogether (such as NDC)?
