### ISSUE TITLE
SPL data

### ISSUE THREAD

**Issue by pozz82** [FDA/openfda#72]
Hello,
launching the SPL pipeline (or any other pipeline depending on SPL data) I get the following error:

```
Running:  aws --profile=default s3 sync s3://openfda-data-spl/data/ ./data/spl/s3_sync
ERR: A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
```

Thus no SPL data can be obtained.
Is that S3 bucket still available?

Thanks and best regards

**Comment by dbuijs** [comment]
I noticed this error with the drug/event endpoint as well. Is it possible that the S3 buckets aren't actually public?

**Comment by pozz82** [comment]
FDA publishes also JSON label files (if I'm not wrong, their are obtained by processing SPL data) but I don't understand how to process them and include in ElasticSearch or use in the present pipelines

**Comment by dbuijs** [comment]
I've had a bit of success working with the JSON downloads, have a look at https://github.com/dbuijs/faers2csv. But it's not for the faint of heart. Any improvements or suggestions would be welcome.

**Comment by mattmo** [comment]
@pozz82 - thanks for raising this. I'm currently discussing this with the team. Will update this issue once I have more to share.

**Comment by mattmo** [comment]
@pozz82 - this is now available here:

s3://download.open.fda.gov/data/spl

This is the same data that is served by the internal bucket s3://openfda-data-spl/data (and by dailymed for that matter). You should be able to update that path and run the pipeline just fine. Please let me know if you have any questions.

**Comment by pozz82** [comment]
Thanks Matt!
I updated the bucket URL in the SPL pipeline and everything is now working perfectly.
