### ISSUE TITLE
Question: download zip files

### ISSUE THREAD

**Issue by yunstat** [FDA/openfda#75]
For the zip files packed at 2016/06/01, I downloaded the file named "2004q1/drug-event-0001-of-0002.json.zip", and found that the first three records of the file have strange receive_date: 
"receivedate": "20100729", 
"receivedate": "20101129", 
"receivedate": "20110614".

Are those zip files packed randomly or by some rules?

**Comment by HansNelsen** [comment]
The drug event downloads are partitioned on an internal key called `@timestamp` which is simply mapped to the drug event key `receiptdate`.  The records should contain all data with a `receiptdate` between 20040101 to 20040401.

**Comment by yunstat** [comment]
Follow-up questions:

do you keep or remove earlier reports from the same safetyid?
or do you combine all reports from the same safetyid?

Thanks

**Comment by HansNelsen** [comment]
The reports are processed in order first to latest and only the latest one is kept.

**Comment by yunstat** [comment]
https://api.fda.gov/drug/event.json?search=receivedate:[20040101+TO+20140131]+AND+safetyreportid:4261828

has 1 match with 
"receivedate": "20040102",
"receiptdate": "20031222"

In the original ASCII 2004Q1, the id has only one record with the same id with
FDA_DT=20140103
MFR_DT=20031222

Does receipt date come from MFR_DT?

**Comment by HansNelsen** [comment]
I do not know the answer to this one. The answer might be in the pdf files that come with the downloads. There is a sort of data dictionary in there that may prove useful in answering this questions. You could also ask the openFDA team, since they are in regular contact with the FDA and they can forward your question on to the internal group responsible for the drug event data.

Good luck.

**Comment by yunstat** [comment]
According to the SGM_NTS file at 2004Q1 to 2012Q3 (LAERS),
A.1.6b receivedate=FDA receive date = (FDA_dt in ASCII)
A.1.7b receiptdate=Manufacturer’s date of receipt of initial information. For non-mfr reports, <receivedate>  is repeated. = (MFT_dt in ASCII)

According to the XML_NTS file in 2012Q4 to 2014Q1 (FAERS)	
A.1.6b receivedate Date report was first received by FDA (Initial FDA Received Date) = (FDA_init_dt in ASCII)
A.1.7b receiptdate Date of most recent report received by FDA (Individual Case FDA Received Date) = (the newest FDA_dt in ASCII)

In conclusion,
Receiptdate <= receivedate before 2012Q3
Receiptdate >= receivedate after 2012Q4

Could It be possible for openFDA to add FDA_dt from ASCII files?

The following table contains the aggregated counts of (receivedate – receiptdate) from total 226 zip files.
Diff(Year) Count
      -22       2
      -19       1
      -18       1
      -16       2
      -15       2
      -14      11
      -13      31
      -12      47
      -11      50
      -10      83
       -9     138
       -8     292
       -7     611
       -6     938
       -5    1669
       -4    3100
       -3    7470
       -2   20847
       -1   79353
        0 3263264
        1 2599034
        2  107729
        3   39024
        4   17173
        5    3445
        6    1641
        7    1005
        8     357
        9      13

The following table contains counts from 2012Q4-2015Q4
Diff(Year) Count
      -22       2
      -19       1
      -18       1
      -16       2
      -15       2
      -14      11
      -13      31
      -12      46
      -11      48
      -10      81
       -9     137
       -8     274
       -7     571
       -6     881
       -5    1602
       -4    2992
       -3    7194
       -2   20235
       -1   76846
        0 2844944

The following table contains counts from zip files 2004Q1 to 2011Q4
Diff(Year) Count
       -2       4
        0  219216
        1 2233320
        2  107729
        3   39024
        4   17173
        5    3445
        6    1641
        7    1005
        8     357
        9      13

The following table contains counts from zip files 2012Q1 to 2012Q3
Diff(Year) Count
      -12      1
      -11      2
      -10      2
       -9      1
       -8     18
       -7     40
       -6     57
       -5     67
       -4    108
       -3    276
       -2    608
       -1   2507
        0 199104
        1 365714

**Comment by dkrylovsb** [comment]
@yunstat, the pipeline pulls drug adverse events from FAERS XML/SGML files, not the ASCII ones (the latter is only used for report id to case number conversion in some cases). So in the example you provided the dates come from AERS_SGML_2004q1.zip/sgml/ADR04M01.SGM:

```
   <receivedateformat>102</receivedateformat>
   <receivedate>20040102</receivedate>
   <receiptdateformat>102</receiptdateformat>
   <receiptdate>20031222</receiptdate>
```
   
So the drug event data should not be affected by the change in the ASCII structure you described.

**Comment by yunstat** [comment]
Thank you. After seeing the earlier response, I remember that openFDA did not alter the data. I checked the NTS files to search the reason of having smaller receipt_date. 

The FAERS system is started at 2012 Q4. Before that, the system is called AERS, or LAERS. 
From 2012Q4 to 2016Q1, the NTS file describes
- A.1.6b receivedate = Date report was first received by FDA (Initial FDA Received Date)
- A.1.7b receiptdate = Date of most recent report received by FDA 
From 2004Q1 to 2012Q3, the NTS file describes
- A.1.6b receivedate = FDA receive date
- A.1.7b receiptdate = Manufacture's date of receipt of initial information. For non-mfr reports, receiptdate is repeated.

Therefore, receivedate >= receiptdate before 2012Q3, and receivedate <= receiptdate after 2012Q4. This solved my questions of having receiptdate smaller than receivedate at 2004.

I have been think about the effect on aggregated counts. This is like a shift of time frame. My observation on the effect is small.

**Comment by yunstat** [comment]
The format of FAERS xml files is recommended by the DTD in ICH E2b/M2 V 2.1 standard. (2001)
The DTD describes
- A.1.6b receivedate = CCYYMMDD = Date report was first received from source
- A.1.7b receiptdate = CCYYMMDD = Date of receipt of the most recent information for this report

**Comment by cerdman** [comment]
Note that E2B(R3) is currently in use and not v2 - http://www.fda.gov/downloads/Drugs/GuidanceComplianceRegulatoryInformation/Guidances/UCM275638.pdf

**Comment by yunstat** [comment]
I have been thinking about the effect on aggregated counts. 
Assume constant number of reports in each quarter.
The count by receive may look like:
receivedt <- 2004+runif(100000)*12 
diff <-  -rexp(100000,3)*(receivedt >=2012.75)
hist(receivedt+diff , xlim=c(2004,2016), breaks=48, prob=TRUE)



The effect of counting by receivedate
y <- runif(100000)*12+2004
diff <- -rexp(100000,3)*(y>2012.75)
hist(y+diff, xlim=c(2004,2016), breaks=48)

**Comment by yunstat** [comment]
I have been thinking about the effect on aggregated counts. 
Assume constant number of reports in each quarter.
The count by receive may look like:
receivedt <- 2004+runif(100000)*12 
diff <- -rexp(100000,1)*(receivedt >=2012.75)
hist(receivedt+diff , xlim=c(2004,2016), breaks=48, prob=TRUE)

The count by receiptdate may look like:
receivedt <- 2004+runif(100000)*12 
diff <- -rexp(100000,3)*(receivedt >=2012.75)
hist(receivedt+diff , xlim=c(2004,2016), breaks=48, prob=TRUE)

**Comment by yunstat** [comment]
I have been thinking about the effect on aggregated counts. 
Assume constant number of reports in each quarter.
The count by receive may look like:
receivedt <- 2004+runif(100000)*12 
diff <- -rexp(100000,0.8)*(receivedt >=2012.75)
hist(receivedt+diff , xlim=c(2004,2016), breaks=48, prob=TRUE)

The count by receipt date may look like:
receiptdt <- 2004+runif(100000)*12 
diff <- -rexp(100000,0.8)*(receiptdt < 2012.75)
hist(receiptdt +diff , xlim=c(2004,2016), breaks=48, prob=TRUE)

**Comment by pozz82** [comment]
@cerdman I just downloaded 2016q1 XML's zip file, and in both PDF and XML files it is stated that version 2.1 is used, not v3.

PDF:

> is compliant with the DTD DCL files that are published as part of the ICH
> E2b/M2 version 2.1 standard

XML:

> \<messageformatversion\>2.1\</messageformatversion\>
