### ISSUE TITLE
Question: search result - odd case report

### ISSUE THREAD

**Issue by yunstat** [FDA/openfda#76]
Hi, 

when I looking into the result of the following query, the generic name "rasburicase" is listed under the field activesubstancename. should I consider the two fields openfda.generic_name and activesubstancename equal? Thank you very much.

https://api.fda.gov/drug/event.json?search=receivedate:[20040101+TO+20160601]+AND+patient.drug.openfda.generic_name.exact=rasburicase&limit=1

(One of the drugs listed in that case)
{
            "drugstartdateformat": "102",
            "drugindication": "PROPHYLAXIS",
            "activesubstance": {
              "**activesubstancename**": "**RASBURICASE**"
            },
            "drugadministrationroute": "042",
            "drugcharacterization": "2",
            "drugstartdate": "20140120",
            "drugstructuredosagenumb": "35.2",
            "drugdosagetext": "35.2 MG, UNKNOWN FREQ.",
            "drugstructuredosageunit": "003",
            "medicinalproduct": "FASTURTEC"
},

**Comment by HansNelsen** [comment]
The `activesubstancename ` was added circa 2013 by the FDA. As such, it is not on each and every document. In addition to that fact, the current matching logic for annotating a `patient.drug` record is solely against the `patient.drug.medicinalproduct` field, so it does not take the new field into account. 

This is just my opinion, but I would use the `patient.drug.openfda.generic_name.exact` if it exists and if it does not, see if the `activesubstancename` exists and use that. 

Long term, I would consider adding a feature request or doing a PR to include the `activesubstancename` in the annotation matching logic. Then you could use the `generic_name` as the sole source.

**Comment by yunstat** [comment]
2 more questions:
1. is it true that returned counts are exact (count all records kept in the openFDA database) not approximated?
2. is it true that the structure of openfda field is regular, not nested?

**Comment by HansNelsen** [comment]
The counting in the API is a correct but done as an estimate rather than an expensive pure count. When using the estimate approach results in degradation of the last few counts in the result, so, as a work around, the API requests 1000 extra (limit + 1000) and then snips off the end. So they are estimates, but they are accurate.

There are no nested types in the entire API.
