### ISSUE TITLE
OpenFDA Mapping to infliximab (and possibly others) missing

### ISSUE THREAD

**Issue by dbuijs** [FDA/openfda#77]
Some time in the last few months the openfda sections for adverse event reports to the drug infliximab got dropped. 

https://api.fda.gov/drug/event.json?search=patient.drug.openfda.generic_name:%22infliximab%22&limit=5&skip=0

gives:

```
{
  "error": {
  "code": "NOT_FOUND",
  "message": "No matches found!"
  }
}
```

The reports are still there:

https://api.fda.gov/drug/event.json?search=%22infliximab%22&limit=5&skip=0

(Partial result):

```
"meta": {
    "disclaimer": "Do not rely on openFDA to make decisions regarding medical care. While we make     every effort to ensure that data is accurate, you should assume all results are unvalidated. We may limit     or otherwise restrict your access to the API in line with our Terms of Service.",
     "terms": "https://open.fda.gov/terms/",
   "license": "https://open.fda.gov/license/",
   "last_updated": "2015-01-01",
   "results": {
     "skip": 0,
     "limit": 5,
    "total": 28853
   }
```

And:

```
 {
        "drugcharacterization": "2",
        "drugstructuredosagenumb": "5",
        "drugdosagetext": "5 MG/KG",
        "drugrecurreadministration": "3",
        "drugstructuredosageunit": "007",
        "medicinalproduct": "INFLIXIMAB"
      }
```

This drug in particular was mapped just fine as recently as a few months ago, and you can see it in the data archived here: https://doi.org/10.5281/zenodo.45589

This breaks the additional tools: https://openfda.shinyapps.io/RR_D/

**Comment by dkrylovsb** [comment]
Thank you for bringing this to our attention. We'll investigate and report back with findings.

**Comment by dkrylovsb** [comment]
@dbuijs , we found out that, even though infliximab is present in the NDC data set, the most recent SPL file is missing from the SPL data set that serves as an input to OpenFDA pipelines. This is causing harmonization record for this particular drug to be empty. 

We are working on fixing this; sorry about the inconvenience.

**Comment by dbuijs** [comment]
Thanks! Do you have any sense of how many drugs/products have been impacted by this issue and when it can be resolved?

**Comment by dkrylovsb** [comment]
Humira is another drug that has also been impacted by this issue. We expect a resolution this week.

**Comment by cerdman** [comment]
Can you describe (if possible) how the openFDA SPL data set is constructed and maintained?

**Comment by dkrylovsb** [comment]
https://api.fda.gov/drug/event.json?search=patient.drug.openfda.generic_name:%22infliximab%22&limit=5&skip=0 now returns more than 100K results as expected.
