### ISSUE TITLE
Medical Device Data

### ISSUE THREAD

**Issue by jltemple** [FDA/openfda#78]
Hey all! A little over a month ago, there was an "[OpenFDA Unveils Cache of Medical Device Data](https://open.fda.gov/update/openfda-unveils-cache-of-medical-device-data/)" announcement. Just last week there was an announcement that the [Unique Device Identifier data set is now available](https://twitter.com/openFDA/status/780442502591606784), and it's my understadning that this information would be from the Monthly Full releases available on NLM's [AccessGUDID](https://accessgudid.nlm.nih.gov/download)

Will the code for parsing this GUDID information into OpenFDA be available on this repository like the SPL parsing code?

Thanks!

**Comment by dkrylovsb** [comment]
The code is now available.
