### ISSUE TITLE
Duplicated patient's records in device/event

### ISSUE THREAD

**Issue by mlazarew** [FDA/openfda#80]
It seems that in the [open.fda.gov/device/event](https://open.fda.gov/device/event/) the patients have duplicated records.

  "patient": [
    {
      "sequence_number_treatment": [
        ""
      ],
      "patient_sequence_number": "1",
      "date_received": "19920310",
      "sequence_number_outcome": [
        "1. R"
      ]
    },
    {
      "sequence_number_treatment": [
        ""
      ],
      "patient_sequence_number": "1",
      "date_received": "19920310",
      "sequence_number_outcome": [
        "1. R"
      ]
    }
  ],

**Comment by debovis** [comment]
For a more readable example of the above JSON

```"patient": [
   {
      "sequence_number_treatment": [""],
      "patient_sequence_number": "1",
      "date_received": "19920310",
      "sequence_number_outcome": ["1. R"]
   },
   {
      "sequence_number_treatment": [""],
      "patient_sequence_number": "1",
      "date_received": "19920310",
      "sequence_number_outcome": ["1. R"]
   }
],```

**Comment by gundalar** [comment]
@mlazarew the duplicate patient records issue in the [device/event API ](https://open.fda.gov/device/event/) is fixed now. Thanks for bringing it to our attention.
