### ISSUE TITLE
Drug labels missing (ex: Kymriah and Yescarta)

### ISSUE THREAD

**Issue by akravetz** [FDA/openfda#89]
Hello,
It appears as though some drug labels are missing.  Specifically I cannot find either Kymriah or Yescarta searching by their brand or generic name.  Both drugs were approved in 2017.  I have downloaded the complete label dataset from https://download.open.fda.gov/drug/label/drug-label-000X-of-0007.json.zip and confirm that neither terms appear in the complete dataset at all. 

Example search:
`https://api.fda.gov/drug/label.json?api_key=XXXX&search=kymriah`

edit: I have confirmed that the kymriah label XML files are present on the SPL S3 bucket:

`
s3://download.open.fda.gov/data/spl/11dc1c28-0cf5-4290-b499-eb5391a232c2
s3://download.open.fda.gov/data/spl/22dc1c28-0cf5-4290-b499-eb5391a232c2
s3://download.open.fda.gov/data/spl/60770743-9a0b-4793-a4c7-8ebcd2d02080
`

**Comment by akravetz** [comment]
Question answered here:

**Comment by dkrylovsb** [comment]
@akravetz Unfortunately, not at this point. I'd have to first inquiry within the FDA about why cellular therapies were excluded in the first place (I'm not the original writer of that code), and obtain a permission to include them. I can go this route if it is important to index these drugs.

**Comment by akravetz** [comment]
@dkrylovsb  no problem, I understand.  These are important drug types to have, especially as more manufacturers are getting into this space.  Internally, we'll probably fork openfda and run our own pipeline until this is merged.  I opened a PR, just so we have a place to have the conversation. 

If it's helpful, I'm happy to reach out to someone at FDA to move this forward.  I just need to know who to contact.

Cheers,
Alex

**Comment by dkrylovsb** [comment]
@akravetz Would you be able to email your inquiry to open@fda.hhs.gov?

**Comment by akravetz** [comment]
No problem.  I'm hoping this will be quick to resolve, it looks like cellular therapies aren't even consistently excluded.  Provenge, for example is included.  Would it be best to CC you on the email?  If so, what is your email address?
