### ISSUE TITLE
Medical Device - multiple FEI numbers associated with a single 510(k) number

### ISSUE THREAD

**Issue by Injoonnoh** [FDA/openfda#91]
In the device 510(k) endpoint data (downloadable JSON file on OpenFDA), a single 510(k) number is associated with multiple FDA Establishment Identification (FEI) numbers, and I am not being able to figure out how those multiple FEI numbers are associated with a single 510(k) number. I would greatly appreciate your help.

Below are some more details on how I collected/parsed the data and an example.

I have downloaded the device 510(k) endpoint data (JSON file) from the OpenFDA website (link [here](https://open.fda.gov/tools/downloads/)), and parsed it in R software, using the "jasonlite" package (R code for importing the json file below):

`library(readr)`
`library(jsonlite)`
`data_flat_510k <- fromJSON('device-510k-0001-of-0001.json', flatten = TRUE)`

The device 510(k) endpoint data has 29 fields (i.e., columns), including 510(k) number, device name, applicant name and address, etc. One of these fields is "openfda.fei_number" which is a "list" of the FEI numbers associated with each 510(k) number.

For example, the list of FEI numbers associated with a single 510(k) number "K840424" is: "1048014, 3002808374, 3003915875, 3009211636, 1000587249, 2518902, 1000138054, 1282497"

So, the 510(k) number "K840424" has 8 FEI numbers. If I look this 510(k) number up in the Device Registrations and Listings database (also available/downloadable on OpenFDA), it shows only one medical device establishment, and thus, only one FEI number (which is one of the above listed FEI numbers).

Again, I can't figure out how these FEI numbers are associated with this single 510(k) number, and I would appreciate your help!

**Comment by dkrylovsb** [comment]
`openfda` is the "harmonization" record, and for medical devices harmonization revolves around `product_code`. So in the example you provided the 8 FEI numbers correspond to the product code of `KNZ`, _not_ directly to the 510(k) number. More on this here: https://github.com/FDA/openfda/blob/master/openfda/device_harmonization/pipeline.py

Sorry about the confusion.
