### ISSUE TITLE
Is there a start parameter for queries?

### ISSUE THREAD

**Issue by Shane-Neeley** [FDA/openfda#92]
Since there is now a skip limit of 25,000, how can I get results for a large query after 25,000?

Say I want labels from 25k to 30k:

`https://api.fda.gov/drug/label.json?api_key=<my key>&search=effective_time:[19800101+TO+20180815]&limit=50&skip=5000&start=25000`

I see in this code there is no valid start parameter?
https://github.com/FDA/openfda/blob/c1049ed791770e81e8fa370c68495291016a0a74/api/faers/api_request.js

Thanks

**Comment by dkrylovsb** [comment]
Unfortunately, not at this time. Please see if you could narrow down the query to produce fewer labels.
