### ISSUE TITLE
API request addition

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#95]
I think this is the wrong place to look for this but idk where else to put it. In the FDA recall database they give a recall contact for people to call. This information is not in the enforcement API or the recall API. Is this something that yall would consider adding?

https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRES/res.cfm?id=161767
The information is labeled as "For Additional Information Contact"

**Comment by dkrylovsb** [comment]
We'll inquiry within the FDA about whether it could be added to the data set.

**Comment by CalebYates1** [comment]
Hi, I was wondering if this is a realistic idea to get this information.

**Comment by maksle** [comment]
The `Action` field presented in the link above is missing from the openFDA records. Is it also not provided by FDA?

Sorry, some additional questions if I may
- Is the raw data provided by FDA to openFDA for the datasets available to the public? I have only seen raw data files provided for Maude, and for example the s3://device-recall-data used in openFDA code does not accessible.
- It appears that results from the FDA search at https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfres/res.cfm such as the link posted by the OP are from the recalls-enforcement db, not the recalls db? Can you clarify for me the separation of these datasets?

Thank you!

**Comment by dkrylovsb** [comment]
We receive Device Recall information via an internal FDA channel, which contains fewer fields than what's available in the [recall database online](https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRES/res.cfm), unfortunately. We are working with the FDA on remediating this. 

The raw data is not currently available to the general public.

https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfres/res.cfm is the Recalls Database. Enforcement Reports are at https://www.accessdata.fda.gov/scripts/ires/index.cfm. [This page](https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts/enforcement-reports) outlines the differences between the recalls and recall enforcement reports.

**Comment by dkrylovsb** [comment]
This has been implemented; see [here](https://open.fda.gov/apis/device/recall/searchable-fields/) for more details.
