### ISSUE TITLE
MAUDE events information update

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#96]
Looking into certain events that are in the FDA MAUDE database, but it seems like the API isnt fully update for all September events. Is there a delay?

**Comment by dkrylovsb** [comment]
We update once a week, so may get a bit behind. I'll force a refresh now.

**Comment by CalebYates1** [comment]
I am unsure how long the refresh take, but I am still unable to see the results. I have this result within the MAUDE database ( https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfMAUDE/detail.cfm?mdrfoi__id=7899517&pc=MAX)  and cannot find it within the API ( https://api.fda.gov/device/event.json?search=device.model_number.exact:CIE3-11-24-00&limit=100 ).

**Comment by dkrylovsb** [comment]
Yup, the refresh is still in progress. I will report back once done.

**Comment by dkrylovsb** [comment]
The updates finally went through; sorry about the delay.
