### ISSUE TITLE
Update needed for Enforcement API

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#97]
I am unable to find this recall on the enforcement API, am I just missing something?
https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRES/res.cfm?id=167156

**Comment by dkrylovsb** [comment]
All openFDA datasets except NSDE update weekly. So Enforcement might be a bit behind. Our next weekly update should clear this (I will verify).

**Comment by dkrylovsb** [comment]
Done.
