### ISSUE TITLE
Feature Request: Adding the "For Additional Information Contact" into the Recall or enforcement database

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#98]
Within the Recall database, there is information for a contact about recalls. It is labeled "For additional Information contact". I think it would be amazing if this was to be added to the API. I am attaching a picture below with the information I am talking about highlighted.
![screen shot 2018-11-07 at 3 16 02 pm](https://user-images.githubusercontent.com/43623659/48161481-47ad8900-e2a0-11e8-8df0-90fce43e9a9f.png)

**Comment by dkrylovsb** [comment]
We will inquiry within the FDA on whether this field could be added to the dataset file supplied to us for processing.

**Comment by dkrylovsb** [comment]
@CalebYates1 Would you be please submit your request by email to open@fda.hhs.gov?

**Comment by CalebYates1** [comment]
Sure thing! @dkrylovsb

**Comment by dkrylovsb** [comment]
Thank you

Sincerely,
Denis Krylov
Director of Software Engineering
SemanticBits, LLC
703.429.4293
denis.krylov@semanticbits.com
CMMI Level 3 Appraised & ISO 9001:2015 Certified

**Comment by CalebYates1** [comment]
Hello, I emailed about this improvement and never received a response about it and wanted to ensure that an email was received.

**Comment by dkrylovsb** [comment]
Done: see [here](https://open.fda.gov/apis/device/recall/searchable-fields/) for more details.
