### ISSUE TITLE
Difficulty with count and .exact

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#99]
Using the count feature to count device_description within the udi database. I was unable to get the .exact to work with it and see results
![screen shot 2018-11-08 at 9 43 41 am](https://user-images.githubusercontent.com/43623659/48209569-22ba2400-e33b-11e8-9cf8-e9c77ae798e0.png)
![screen shot 2018-11-08 at 9 44 00 am](https://user-images.githubusercontent.com/43623659/48209572-22ba2400-e33b-11e8-9d40-0cb06ce24b71.png)

**Comment by dkrylovsb** [comment]
`device_description` does not have an "exact" field, which is likely an omission on our part. We will work on getting it added and report back once it is available in Production.

**Comment by dkrylovsb** [comment]
This is fixed. `curl -g https://api.fda.gov/device/udi.json?count=device_description.exact`
